AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  FunctionName:
    Type: String
    Default: LambdaVersionFinder
    Description: The name of the Lambda function

Resources:
  LambdaVersionFinderFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref FunctionName
      Handler: lambda_function.get_highest_version
      Runtime: python3.12
      CodeUri: src
      Description: 'Handles incoming data submissions from CognitoForms'
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::905418480469:policy/PermissionsForLambdaVersionFinder
      Tracing: Active  # Enable AWS X-Ray tracing if needed

  LiveAlias:  # Create the alias
    Type: 'AWS::Lambda::Alias'
    Properties:
      FunctionName: !Ref LambdaVersionFinderFunction
      FunctionVersion: '$LATEST'  # Always point to the latest version
      Name: live